spring:
  security:
    user:
      name: admin
      password: admin
      roles: USER

  jms:
    listener:
      acknowledge-mode: client
      auto-startup: true
      concurrency: 1
      max-concurrency: 1
    cache:
      enabled: false

sync:
  settingsLocation: settings.yml
  pollingCron: 0 0 0 1 * ?
  notificationChannelProperties: