name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew :documentation:asciidoctor

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: |
            documentation/build/docs
            !documentation/build/docs/.asciidoctor

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: documentation/build/docs
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.WIKI_ACCESS_TOKEN }}